import { TeamMember } from '@/types';

export const teamMembers: TeamMember[] = [
  {
    id: 'partner-1',
    slug: 'socio-director-1',
    role: 'partner',
    title: 'Socio Director',
    name: '[NOMBRE PENDIENTE DE CONFIRMACIÓN POR EL CLIENTE]',
    bio: '[BIOGRAFÍA PENDIENTE DE CONFIRMACIÓN POR EL CLIENTE]',
    practiceAreas: ['Derecho Civil', 'Derecho Mercantil', 'Amparo'],
    isPlaceholder: true,
  },
  {
    id: 'partner-2',
    slug: 'socio-director-2',
    role: 'partner',
    title: 'Socia / Socio Directora',
    name: '[NOMBRE PENDIENTE DE CONFIRMACIÓN POR EL CLIENTE]',
    bio: '[BIOGRAFÍA PENDIENTE DE CONFIRMACIÓN POR EL CLIENTE]',
    practiceAreas: ['Derecho Familiar', 'Derecho Penal', 'Amparo'],
    isPlaceholder: true,
  },
  {
    id: 'associate-1',
    slug: 'abogado-asociado-1',
    role: 'associate',
    title: 'Abogado Asociado',
    name: '[NOMBRE PENDIENTE DE CONFIRMACIÓN POR EL CLIENTE]',
    bio: '[BIOGRAFÍA PENDIENTE DE CONFIRMACIÓN POR EL CLIENTE]',
    practiceAreas: ['Derecho Civil'],
    isPlaceholder: true,
  },
  {
    id: 'associate-2',
    slug: 'abogado-asociado-2',
    role: 'associate',
    title: 'Abogada Asociada',
    name: '[NOMBRE PENDIENTE DE CONFIRMACIÓN POR EL CLIENTE]',
    bio: '[BIOGRAFÍA PENDIENTE DE CONFIRMACIÓN POR EL CLIENTE]',
    practiceAreas: ['Derecho Mercantil'],
    isPlaceholder: true,
  },
  {
    id: 'associate-3',
    slug: 'abogado-asociado-3',
    role: 'associate',
    title: 'Abogado Asociado',
    name: '[NOMBRE PENDIENTE DE CONFIRMACIÓN POR EL CLIENTE]',
    bio: '[BIOGRAFÍA PENDIENTE DE CONFIRMACIÓN POR EL CLIENTE]',
    practiceAreas: ['Derecho Familiar'],
    isPlaceholder: true,
  },
  {
    id: 'associate-4',
    slug: 'abogado-asociado-4',
    role: 'associate',
    title: 'Abogado Asociado',
    name: '[NOMBRE PENDIENTE DE CONFIRMACIÓN POR EL CLIENTE]',
    bio: '[BIOGRAFÍA PENDIENTE DE CONFIRMACIÓN POR EL CLIENTE]',
    practiceAreas: ['Derecho Penal'],
    isPlaceholder: true,
  },
  {
    id: 'associate-5',
    slug: 'abogado-asociado-5',
    role: 'associate',
    title: 'Abogada Asociada',
    name: '[NOMBRE PENDIENTE DE CONFIRMACIÓN POR EL CLIENTE]',
    bio: '[BIOGRAFÍA PENDIENTE DE CONFIRMACIÓN POR EL CLIENTE]',
    practiceAreas: ['Amparo'],
    isPlaceholder: true,
  },
];
